spring:
  application:
    name: item-service

    
#server:#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
    instance: 
      prefer-ip-address: true #使用ip地址注册,而不是主机名
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
        #instance-id:注册后在列表中显示的名称
--- 
spring:
  profiles: item1
  
server: 
  port: 8001
---
spring:
  profiles: item2
  
server:
  port: 8002 